name: BSR

on:
  push:
    tags:
      - v**

jobs:
  buf:
    name: Buf

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push
        uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          input: proto
          lint: false
          format: false
          breaking: false
          push: true